CREATE TABLE Reservation_Audit (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OperationType VARCHAR2(10),
    OperationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OldValues_JSON CLOB CHECK (OldValues_JSON IS JSON),
    NewValues_JSON CLOB CHECK (NewValues_JSON IS JSON)
);
----
CREATE OR REPLACE TRIGGER Trg_Audit_Reservation_JSON
AFTER
INSERT
    OR
UPDATE
    OR DELETE ON Reservation FOR EACH ROW
DECLARE v_old_json CLOB;
v_new_json CLOB;
v_op_type VARCHAR2(10);
BEGIN IF INSERTING THEN v_op_type := 'INSERT';
ELSIF UPDATING THEN v_op_type := 'UPDATE';
ELSIF DELETING THEN v_op_type := 'DELETE';
END IF;
IF UPDATING
OR DELETING THEN v_old_json := JSON_OBJECT(
    'CustomerID' VALUE :OLD.CustomerID,
    'ReservationDate' VALUE TO_CHAR(:OLD.ReservationDate, 'YYYY-MM-DD'),
    'ReservationTime' VALUE :OLD.ReservationTime,
    'Period' VALUE :OLD.Period,
    'Occasion' VALUE :OLD.Occasion,
    'Instructions' VALUE :OLD.Instructions,
    'Token' VALUE :OLD.Token,
    'AccessCode' VALUE :OLD.AccessCode ABSENT ON NULL
);
END IF;
IF INSERTING
OR UPDATING THEN v_new_json := JSON_OBJECT(
    'CustomerID' VALUE :NEW.CustomerID,
    'ReservationDate' VALUE TO_CHAR(:NEW.ReservationDate, 'YYYY-MM-DD'),
    'ReservationTime' VALUE :NEW.ReservationTime,
    'Period' VALUE :NEW.Period,
    'Occasion' VALUE :NEW.Occasion,
    'Instructions' VALUE :NEW.Instructions,
    'Token' VALUE :NEW.Token,
    'AccessCode' VALUE :NEW.AccessCode ABSENT ON NULL
);
END IF;
INSERT INTO Reservation_Audit (OperationType, OldValues_JSON, NewValues_JSON)
VALUES (v_op_type, v_old_json, v_new_json);
END;