-- Allow analyzing reservations over time
CREATE TABLE Dim_Time (
    TimeID NUMBER PRIMARY KEY,
    FullDate DATE,
    Year NUMBER,
    Quarter NUMBER,
    Month NUMBER,
    Week NUMBER,
    Day NUMBER,
    DayOfWeek VARCHAR2(15)
);
-- Describes the physical location of the reservation, down to the specific table
CREATE TABLE Dim_Location (
    LocationDimID NUMBER PRIMARY KEY,
    TableID NUMBER,
    LocationName VARCHAR2(255),
    SpotNumber NUMBER
);
-- Provides details about the customer who made the reservation
CREATE TABLE Dim_Customer (
    CustomerDimID NUMBER PRIMARY KEY,
    OriginalCustomerID NUMBER,
    CustomerName VARCHAR2(255),
    PhoneNumber VARCHAR2(50),
    Email VARCHAR2(50)
);
-- Describes the reason for the reservation (e.g., Birthday, Business Dinner)
CREATE TABLE Dim_Occasion (
    OccasionDimID NUMBER PRIMARY KEY,
    OccasionName VARCHAR2(255)
);
-- stores the primary business measurements
CREATE TABLE Fact_Reservations (
    FactID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TimeID NUMBER REFERENCES Dim_Time(TimeID),
    LocationDimID NUMBER REFERENCES Dim_Location(LocationDimID),
    CustomerDimID NUMBER REFERENCES Dim_Customer(CustomerDimID),
    OccasionDimID NUMBER REFERENCES Dim_Occasion(OccasionDimID),
    Duration_Minutes NUMBER,
    Reservation_Count NUMBER DEFAULT 1
);