-- CREATE MATERIALIZED VIEW mv_customer_reservations BUILD IMMEDIATE REFRESH FAST ON DEMAND AS
-- SELECT c.C_Name,
--     l.Name AS Location_Name,
--     c.ROWID AS c_rid,
--     rt.ROWID AS rt_rid,
--     t.ROWID AS t_rid,
--     l.ROWID AS l_rid
-- FROM Customer c,
--     ReservedTable rt,
--     RestaurantTable t,
--     Location l
-- WHERE c.CustomerID = rt.CustomerID
--     AND rt.TableID = t.TableID
--     AND t.LocationID = l.LocationID;